#pragma config(Sensor, in1,    rPot,           sensorPotentiometer)
#pragma config(Sensor, in2,    turningGyro,    sensorGyro)
#pragma config(Sensor, in3,    lineInnerL,     sensorLineFollower)
#pragma config(Sensor, in4,    lineInnerR,     sensorLineFollower)
#pragma config(Sensor, in5,    lineOuterL,     sensorLineFollower)
#pragma config(Sensor, in6,    lineOuterR,     sensorLineFollower)
#pragma config(Sensor, dgtl1,  sonicLeft,      sensorSONAR_mm)
#pragma config(Sensor, dgtl3,  sonicRight,     sensorSONAR_mm)
#pragma config(Motorm  port1,           lDrive3,       tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port2,           lDrive1,       tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port3,           lDrive2,       tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port4,           leftLift1,     tmotorVex393, openLoop)
#pragma config(Motor,  port5,           leftLift2,     tmotorVex393, openLoop)
#pragma config(Motor,  port6,           rightLift1,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           rightLift2,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port10,          rightLift3,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           rDrive2,       tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port9,           rDrive1,       tmotorVex393HighSpeed, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

// Include headers
#include "/headers/definitions.h"

#include "/headers/main.h"

#include "/headers/variables.h"

// Include files
#include "Vex_Competition_Includes.c" // Do not modify

#include "/files/usercontrol.c"

#include "/files/autonomous.c"

#include "/files/preauton.c"
