/*
	Temporary test code to find the number of revolutions in degrees
	per second of the lift height (for some equation). 

	Only temporary to find values, will be removed after.
*/
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    PotentiometerLL, sensorPotentiometer)
#pragma config(Sensor, in2,    PotentiometerRL, sensorPotentiometer)
#pragma config(Sensor, in3,    ,               sensorGyro)
#pragma config(Sensor, in4,    LineL,          sensorLineFollower)
#pragma config(Sensor, in5,    LineM,          sensorLineFollower)
#pragma config(Sensor, in6,    LineR,          sensorLineFollower)
#pragma config(Sensor, dgtl1,  UltrasonicL,    sensorSONAR_mm)
#pragma config(Sensor, dgtl3,  UltrasonicR,    sensorSONAR_mm)
#pragma config(Sensor, dgtl5,  PistonClaw,     sensorDigitalIn)
#pragma config(Sensor, dgtl6,  EIN,            sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           RDF,           tmotorVex393, openLoop, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port2,           RDB,           tmotorVex393, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port3,           LLU,           tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           LLD,           tmotorVex393, openLoop)
#pragma config(Motor,  port5,           RLU,           tmotorVex393, openLoop)
#pragma config(Motor,  port6,           RLD,           tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           RIN,           tmotorVex393, openLoop)
#pragma config(Motor,  port8,           LIN,           tmotorVex393, openLoop)
#pragma config(Motor,  port9,           LDB,           tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_4, 1000)
#pragma config(Motor,  port10,          LDF,           tmotorVex393, openLoop, encoder, encoderPort, I2C_3, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

//Main Header
#include "main.h"

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

//Pre Auton
#include "preauton.c"

//Autonomous
#include "autonomous.c"

int leftSideUp[6];
int leftSideDown[6];

task usercontrol()
{
	int counter = 0;
	while (true)
	{
		if (counter == 6)
		{
			break;
		}
		motor[LLU] = 127;
		motor[RLD] = 127;
		motor[RLU] = 127;
		motor[LLD] = 127;
		leftSideUp[counter] = PotL;
		rightSideUp[counter] = PotR;
		counter += 1;
		wait1Msc(1000);
	}
}
