#pragma config(Motor,  port1,           LDB,           tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port2,           RDB,           tmotorVex393, openLoop)
#pragma config(Motor,  port3,           LL1,           tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           LL2,           tmotorVex393, openLoop)
#pragma config(Motor,  port5,           RL1,           tmotorVex393, openLoop)
#pragma config(Motor,  port6,           RL2,           tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           RDF,           tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port10,          LDF,           tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{


}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop
	int rightLift;
	int leftLift;
	int leftDF;
	int rightDF;
	int leftDB;
	int rightDB;

	while (true)
	{
	//Lift
		//Get Controller Values
			leftLift=(vexRT[Btn5U]-vexRT[Btn5D])*127;
			rightLift=(vexRT[Btn5U]-vexRT[Btn5D])*127;
		//Give Lift Values
			motor[LL1] = leftLift+10;
			motor[LL2] = leftLift+10;
			motor[RL1] = rightLift+10;
			motor[RL2] = rightLift+10;
		//Drive
			//Left Stick Control (Strafe and movement)
				leftDF=vexRT[Ch3]+vexRT[Ch4];
				leftDB=vexRT[Ch3]-vexRT[Ch4];
				rightDF=vexRT[Ch3]-vexRT[Ch4];
				rightDB=vexRT[Ch3]+vexRT[Ch4];
			//Right Stick Control (Turning)
				leftDF=leftDF+vexRT[Ch1];
				leftDB=leftDB+vexRT[Ch1];
				rightDF=rightDF-vexRT[Ch1];
				rightDB=rightDB-vexRT[Ch1];
		//Give motors values
			motor[LDF]=leftDF;
			motor[LDB]=leftDB;
			motor[RDF]=rightDF;
			motor[RDB]=rightDB;
	}
}
