#pragma config(Motor,  port1,           leftDriveA,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port2,           leftDriveB,    tmotorVex393, openLoop)
#pragma config(Motor,  port3,           leftDriveC,    tmotorVex393, openLoop,reversed)
#pragma config(Motor,  port4,           leftLift,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           leftIntake,    tmotorVex393, openLoop)
#pragma config(Motor,  port6,           rightIntake,   tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           rightLift,     tmotorVex393, openLoop)
#pragma config(Motor,  port8,           rightDriveC,   tmotorVex393, openLoop)
#pragma config(Motor,  port9,           rightDriveB,   tmotorVex393, openLoop)
#pragma config(Motor,  port10,          rightDriveA,   tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop
	short left, right, lift, intake;
	while (true)
	{
	  left = vexRT[Ch3] + vexRT[Ch4];
	  right = vexRT[Ch3] - vexRT[Ch4];
	  lift = vexRT[Ch3Xmtr2];
	  intake = vexRT[Ch2Xmtr2];

	  motor[leftDriveA] = left;
	  motor[leftDriveB] = left;
	  motor[leftDriveC] = left;

  motor[rightDriveA] = right;
	  motor[rightDriveB] = right;
	  motor[rightDriveC] = right;

	  motor[leftLift] = lift;
	  motor[rightLift] = lift;

	  motor[leftIntake] = intake;
	  motor[rightIntake] = intake;
	}
}
