#pragma config(Sensor, in8,    pot,            sensorPotentiometer)
#pragma config(Motor,  port1,           leftDriveA,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port2,           leftDriveB,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           leftDriveC,    tmotorVex393, openLoop)
#pragma config(Motor,  port4,           leftLift,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           leftIntake,    tmotorVex393, openLoop)
#pragma config(Motor,  port6,           rightIntake,   tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           rightLift,     tmotorVex393, openLoop)
#pragma config(Motor,  port8,           rightDriveC,   tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           rightDriveB,   tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port10,          rightDriveA,   tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////
#define round(x) ((x)>=0?(long)((x)+0.5):(long)((x)-0.5))
const int expScalingVal = 30; //Change on driver request
bool expCtrlEnabled = true; //Switch for log drive

int expCtrl(int input) //input from value, mod is set to driver preferences
{
	if (expCtrlEnabled)
	{
		int sign = input / abs(input);

		input = abs(input);

		float scalingVal = 127.0 / (expScalingVal - 1);
		float percentMax = input / 127.0;
		float expMod = (float)(pow(expScalingVal, percentMax) - 1);
		int output = (int)round(scalingVal * expMod * sign);
		return(output);
	}
	else
	{
		return(input);
	}
}

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	  motor[leftDriveA] = 127;
	  motor[leftDriveB] = 127;
	  motor[leftDriveC] = 127;
  	motor[rightDriveA] = 127;
  	motor[rightDriveB] = 127;
	  motor[rightDriveC] = 127;
	  wait1Msec(1000);
	  motor[leftDriveA] = 0;
	  motor[leftDriveB] = 0;
	  motor[leftDriveC] = 0;
  	motor[rightDriveA] = 0;
  	motor[rightDriveB] = 0;
	  motor[rightDriveC] = 0;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop
	short left, right, lift, intake;
	while (true)
	{
			//Limit movement to one direction
	  //left = (vexRT[Ch2] - vexRT[Ch1]);
	  //right = vexRT[Ch2] + vexRT[Ch1];
	  intake = (vexRT[Btn6U]-vexRT[Btn6D])*127;
	  lift = (vexRT[Btn5U]-vexRT[Btn5D])*127+20;

	  if (abs(vexRT[Ch2]) < abs(vexRT[Ch1]))
		{
	  left = -vexRT[Ch1];
	  right = vexRT[Ch1];
		}
		else
		{
	  left = vexRT[Ch2];
	  right = vexRT[Ch2];
		}

	  left=expCtrl(left);
	  right=expCtrl(right);

	  motor[leftDriveA] = left;
	  motor[leftDriveB] = left;
	  motor[leftDriveC] = left;

  	motor[rightDriveA] = right;
  	motor[rightDriveB] = right;
	  motor[rightDriveC] = right;

	  motor[leftLift] = lift;
	  motor[rightLift] = lift;

	  motor[leftIntake] = intake;
	  motor[rightIntake] = intake;
	}
}
