int liftPreset = 0;
int potLTarget = 0;
int potRTarget = 0;
int leftLiftSpeed, rightLiftSpeed;
int leftTrackSpeed. rightTrackSpeed;
int potL, potR;
string driveMode = "tank";
string liftDirection;
bool driveModeButton = false;
bool RLGoalReached, LLGoalReached;
