/*
	Temporary test code to find the number of revolutions in degrees
	per second of the lift height (for some equation).

	Only temporary to find values, will be removed after.
*/
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    potLL, sensorPotentiometer)
#pragma config(Sensor, in2,    potRL, sensorPotentiometer)
#pragma config(Sensor, in3,    turningGyro,               sensorGyro)
#pragma config(Sensor, in4,    lineL,          sensorLineFollower)
#pragma config(Sensor, in5,    lineM,          sensorLineFollower)
#pragma config(Sensor, in6,    lineR,          sensorLineFollower)
#pragma config(Sensor, dgtl1,  ultraL,    sensorSONAR_mm)
#pragma config(Sensor, dgtl3,  ultraR,    sensorSONAR_mm)
#pragma config(Sensor, dgtl12,  piston,     sensorDigitalOut)
#pragma config(Sensor, dgtl6,  encoderIN,            sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  encoderRDB,    sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  encoderRDF,    sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  encoderLDF,    sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  encoderLDB,    sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           driveRF,           tmotorVex393, openLoop, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port2,           driveRB,           tmotorVex393, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port3,           liftLU,           tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           liftLD,           tmotorVex393, openLoop)
#pragma config(Motor,  port5,           liftRU,           tmotorVex393, openLoop)
#pragma config(Motor,  port6,           liftRD,           tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           intakeR,           tmotorVex393, openLoop)
#pragma config(Motor,  port8,           intakeL,           tmotorVex393, openLoop)
#pragma config(Motor,  port9,           driveLB,           tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_4, 1000)
#pragma config(Motor,  port10,          driveLF,           tmotorVex393, openLoop, encoder, encoderPort, I2C_3, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)


#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

typedef struct {
	int frequency;
	int duration;
} sound;

// Its the final countdown sound array. DO NOT TOUCH!!!
const sound finalCountdown[72] = {
	{ 220, 100 }, { 0, 50 }, { 523, 25 }, { 493, 25 }, { 440, 100 },
	{ 261, 100 }, { 174, 100 }, { 0, 50 }, { 587, 25 }, { 523, 25 },
	{ 587, 50 }, { 523, 50 }, { 493, 100 }, { 293, 100 }, { 0, 50 },
	{ 587, 25 }, { 523, 25 }, { 493, 100 }, { 293, 100 }, { 196, 100 },
	{ 0, 50 }, { 493, 25 }, { 440, 25 }, { 493, 50 }, { 440, 50 },
	{ 392, 50 }, { 440, 50 }, { 220, 100 }, { 0, 50 }, { 523, 25 },
	{ 493, 25 }, { 440, 100 }, { 261, 100 }, { 174, 100 }, { 0, 50 },
	{ 587, 25 }, { 523, 25 }, { 587, 50 }, { 523, 50 }, { 493, 100 },
	{ 293, 100 }, { 0, 50 }, { 587, 25 }, { 523, 25 }, { 493, 100 },
	{ 293, 100 }, { 196, 100 }, { 0, 50 }, { 493, 25 }, { 440, 25 },
	{ 493, 50 }, { 440, 50 }, { 392, 50 }, { 440, 50 }, { 349, 100 },
	{ 392, 25 }, { 440, 25 }, { 493, 100 }, { 440, 25 }, { 493, 25 },
	{ 523, 50 }, { 493, 50 }, { 440, 50 }, { 392, 50 }, { 349, 100 },
	{ 440, 100 }, { 392, 200 }, { 523, 50 }, { 587, 50 }, { 523, 50 },
	{ 493, 50 }, { 392, 400 }
};*/

const int finalCountdownFreq[14] = {220, 0, 523, 493, 440, 261, 174, 0, 587, 523, 587, 532, 493, 293};
const int finalCountdownDur[14] = {100, 50, 25, 25, 100, 100, 100, 50, 25, 25, 50, 50, 100, 100};

/*const sound mahnamahna[50] = {

};*/
bool test = false;
//Pre Auton
void pre_auton()
{
}

task autonomous()
{
}


task usercontrol()
{
	PlaySoundFile("final_countdown.wav");
}
